spring:
  application:
    name: url-appender
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 5000
    time-to-live: 60000 # Cache entries expire after 60 seconds

server:
  port: 8080

aws:
  dynamodb:
    endpoint: http://localhost:4566
  region: us-west-2
  accesskey: fakeMyKeyId
  secretkey: fakeSecretAccessKey

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 100
        permittedNumberOfCallsInHalfOpenState: 10
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
    instances:
      dbService:
        baseConfig: default

  retry:
    instances:
      dbService:
        maxAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - software.amazon.awssdk.core.exception.SdkException
