package com.sumeet.later.urlappender.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.*;


import java.io.Serializable;
import java.util.Map;


/**
 * Represents a link entity with details about the original URL,
 * parameters, the new URL generated, and timestamps for creation and updates.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
@DynamoDbBean
public class Link implements Serializable {

    private static final long serialVersionUID = 1L;

    private String originalUrl;
    private Map<String, String> parameters;
    private String newUrl;
    private Long creationTimestamp;
    private Long updateTimestamp;

    /**
     * Gets the original URL provided by the user.
     *
     * @return the original URL
     */
    @DynamoDbPartitionKey
    @DynamoDbAttribute("originalUrl")
    public String getOriginalUrl() {
        return originalUrl;
    }

    /**
     * Sets the original URL.
     *
     * @param originalUrl the original URL
     */
    public void setOriginalUrl(String originalUrl) {
        this.originalUrl = originalUrl;
    }

    /**
     * Gets the parameters to be appended to the URL.
     *
     * @return the parameters map
     */
    @DynamoDbAttribute("parameters")
    public Map<String, String> getParameters() {
        return parameters;
    }

    /**
     * Sets the parameters to be appended to the URL.
     *
     * @param parameters the parameters map
     */
    public void setParameters(Map<String, String> parameters) {
        this.parameters = parameters;
    }

    /**
     * Gets the new URL generated by appending parameters to the original URL.
     *
     * @return the new URL
     */
    @DynamoDbAttribute("newUrl")
    public String getNewUrl() {
        return newUrl;
    }

    /**
     * Sets the new URL.
     *
     * @param newUrl the new URL
     */
    public void setNewUrl(String newUrl) {
        this.newUrl = newUrl;
    }

    /**
     * Gets the timestamp when the link was created.
     *
     * @return the creation timestamp in milliseconds since epoch
     */
    @DynamoDbAttribute("creationTimestamp")
    public Long getCreationTimestamp() {
        return creationTimestamp;
    }

    /**
     * Sets the timestamp when the link was created.
     *
     * @param creationTimestamp the creation timestamp in milliseconds since epoch
     */
    public void setCreationTimestamp(Long creationTimestamp) {
        this.creationTimestamp = creationTimestamp;
    }

    /**
     * Gets the timestamp when the link was last updated.
     *
     * @return the update timestamp in milliseconds since epoch
     */
    @DynamoDbAttribute("updateTimestamp")
    public Long getUpdateTimestamp() {
        return updateTimestamp;
    }

    /**
     * Sets the timestamp when the link was last updated.
     *
     * @param updateTimestamp the update timestamp in milliseconds since epoch
     */
    public void setUpdateTimestamp(Long updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }
}